// ------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion: 14.0.0.0
//  
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code neu generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HtmlReporting.T4
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "G:\Development\src\HtmlReporting\HtmlReporting\T4\CallAbstractT4.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class CallAbstractT4 : AbstractBaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("  \r\n\r\n");
            
            #line 3 "G:\Development\src\HtmlReporting\HtmlReporting\T4\CallAbstractT4.tt"
   
  // Set the base template properties:  
  base.Description = "Description for this derived class";   

  // Run the base template:  
  base.TransformText();    

            
            #line default
            #line hidden
            this.Write("  \r\nEnd material for CallAbstractT4.  \r\n\r\n ");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
