// ------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion: 14.0.0.0
//  
//     Änderungen an dieser Datei können fehlerhaftes Verhalten verursachen und gehen verloren, wenn
//     der Code neu generiert wird.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace HtmlReporting.T4
{
    using System.Linq;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "G:\Development\src\HtmlReporting\HtmlReporting\T4\RuntimeTextTemplate1.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class RuntimeTextTemplate1 : RuntimeTextTemplate1Base
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("<div class=\"block_post\" >\r\n<h2>");
            
            #line 12 "G:\Development\src\HtmlReporting\HtmlReporting\T4\RuntimeTextTemplate1.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Title));
            
            #line default
            #line hidden
            this.Write("</h2> <div class=\"post_info\">\r\n <ul>\r\n <li><p>Date: <a href=\"#\">");
            
            #line 14 "G:\Development\src\HtmlReporting\HtmlReporting\T4\RuntimeTextTemplate1.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Date));
            
            #line default
            #line hidden
            this.Write("</a></p></li>\r\n <li><p>Posted by: <a href=\"#\">");
            
            #line 15 "G:\Development\src\HtmlReporting\HtmlReporting\T4\RuntimeTextTemplate1.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Author));
            
            #line default
            #line hidden
            this.Write("</a></p></li>\r\n <li><p>Category: <a href=\"#\">");
            
            #line 16 "G:\Development\src\HtmlReporting\HtmlReporting\T4\RuntimeTextTemplate1.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(this.Category));
            
            #line default
            #line hidden
            this.Write("</a></p></li>\r\n <li><p>Tags:\r\n");
            
            #line 18 "G:\Development\src\HtmlReporting\HtmlReporting\T4\RuntimeTextTemplate1.tt"

foreach(var tag in this.Tags) {

            
            #line default
            #line hidden
            this.Write("\r\n<a href=\"#\">");
            
            #line 22 "G:\Development\src\HtmlReporting\HtmlReporting\T4\RuntimeTextTemplate1.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tag));
            
            #line default
            #line hidden
            this.Write("</a>");
            
            #line 22 "G:\Development\src\HtmlReporting\HtmlReporting\T4\RuntimeTextTemplate1.tt"
 if (this.Tags.First() != tag && this.Tags.Last() != tag) this.Write(",");
            
            #line default
            #line hidden
            
            #line 23 "G:\Development\src\HtmlReporting\HtmlReporting\T4\RuntimeTextTemplate1.tt"

}

            
            #line default
            #line hidden
            this.Write(" </p></li>\r\n </ul>\r\n </div>\r\n</div> ");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "G:\Development\src\HtmlReporting\HtmlReporting\T4\RuntimeTextTemplate1.tt"

private string _TitleField;

/// <summary>
/// Access the Title parameter of the template.
/// </summary>
private string Title
{
    get
    {
        return this._TitleField;
    }
}

private string _AuthorField;

/// <summary>
/// Access the Author parameter of the template.
/// </summary>
private string Author
{
    get
    {
        return this._AuthorField;
    }
}

private global::System.DateTime _DateField;

/// <summary>
/// Access the Date parameter of the template.
/// </summary>
private global::System.DateTime Date
{
    get
    {
        return this._DateField;
    }
}

private string _CategoryField;

/// <summary>
/// Access the Category parameter of the template.
/// </summary>
private string Category
{
    get
    {
        return this._CategoryField;
    }
}

private global::System.Collections.Generic.List<String> _TagsField;

/// <summary>
/// Access the Tags parameter of the template.
/// </summary>
private global::System.Collections.Generic.List<String> Tags
{
    get
    {
        return this._TagsField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool TitleValueAcquired = false;
if (this.Session.ContainsKey("Title"))
{
    this._TitleField = ((string)(this.Session["Title"]));
    TitleValueAcquired = true;
}
if ((TitleValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Title");
    if ((data != null))
    {
        this._TitleField = ((string)(data));
    }
}
bool AuthorValueAcquired = false;
if (this.Session.ContainsKey("Author"))
{
    this._AuthorField = ((string)(this.Session["Author"]));
    AuthorValueAcquired = true;
}
if ((AuthorValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Author");
    if ((data != null))
    {
        this._AuthorField = ((string)(data));
    }
}
bool DateValueAcquired = false;
if (this.Session.ContainsKey("Date"))
{
    this._DateField = ((global::System.DateTime)(this.Session["Date"]));
    DateValueAcquired = true;
}
if ((DateValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Date");
    if ((data != null))
    {
        this._DateField = ((global::System.DateTime)(data));
    }
}
bool CategoryValueAcquired = false;
if (this.Session.ContainsKey("Category"))
{
    this._CategoryField = ((string)(this.Session["Category"]));
    CategoryValueAcquired = true;
}
if ((CategoryValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Category");
    if ((data != null))
    {
        this._CategoryField = ((string)(data));
    }
}
bool TagsValueAcquired = false;
if (this.Session.ContainsKey("Tags"))
{
    this._TagsField = ((global::System.Collections.Generic.List<String>)(this.Session["Tags"]));
    TagsValueAcquired = true;
}
if ((TagsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Tags");
    if ((data != null))
    {
        this._TagsField = ((global::System.Collections.Generic.List<String>)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public class RuntimeTextTemplate1Base
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
